name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'renovate'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
      - 'feature'
      - 'minor'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'documentation'
      - 'chore'
      - 'patch'
  default: patch

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/^fix:/i'
  - label: 'enhancement'
    branch:
      - '/feat(ure)?\/.+/'
    title:
      - '/^feat:/i'
  - label: 'chore'
    title:
      - '/^chore:/i'

template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
